services:
  - type: web
    name: uber-backend
    env: node
    buildCommand: "./build.sh"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_CONNECT
        sync: false
      - key: GOOGLE_MAPS_API
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false 